#! /usr/bin/python3

import os
import sys
import yaml

with open(os.path.join(os.path.dirname(__file__), 'list.yml')) as f:
    data = yaml.load(f)


class Host:
    def __init__(self, d):
        self.hostname = d['hostname']
        self.ip = d['ip']
        self.keys = d['keys']
        try:
            self.port = d['port']
        except KeyError:
            self.port = None


for host in data:
    try:
        h = Host(host)
    except KeyError as e:
        print('Missing required key "{}"'.format(e), file=sys.stderr)
        sys.exit(1)

    for key in h.keys:
        fmt = {
            'h': h.hostname,
            'i': h.ip,
            'p': h.port,
            'k': key,
        }
        if h.port is None:
            print('{h},{i} {k}'.format(**fmt))
        else:
            print('[{h}]:{p},[{i}]:{p} {k}'.format(**fmt))
