#! /usr/bin/python3

import os
import yaml

with open(os.path.join(os.path.dirname(__file__), 'list.yml')) as f:
    data = yaml.safe_load(f)

for host in data:
    print('Host', host['hostname'])
    print('    StrictHostKeyChecking yes')
    try:
        print('    Port', host['port'])
    except KeyError:
        # default port, leave it.
        pass
